#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

FROM base AS final
WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "Web2023_BE.Web.dll"]